#!/bin/bash
set -e
source meta/stdenv.sh
source jupyter/ipython-env/bin/activate
source meta/jupyter-env.sh
JULIA_KERNEL=$(jupyter kernelspec list | awk '{print $1}' | egrep julia)
jupyter nbconvert \
  --ExecutePreprocessor.kernel_name=$JULIA_KERNEL \
  --ExecutePreprocessor.timeout=600 \
  --to rst \
  --output-dir="$WORKSPACE/notebooks-out" \
  --execute "$@"
