# Example credentials file.
#
# The SSH key is a dummy key that is not in use anywhere.

oscar:
  repo: oscar-system/oscar-ci-results
  key: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAQEAuQSw1PuE9Mfc59cy9qtlEw7f5oTtLiTMxwfn4oZGArHXd81/pU53
    C7277usItrvbteV/rKMbkweKN/cBtSQXls0tqpt536qA0ktaxFZVfMuxmbOHPn2I+Q13y9
    gvQHKtLfHBy5y8PfAXDpR0IO733ah8QFBvkeNE3UPpVGlKEDEQEG96RL4eq81PZl4n7Mts
    PPlufEBZjjmnHbG1mGCa0ISVnxqUjvxV8cvg9alnE05LZblVrGDwvj47eEtDqloE/O3qD4
    GtX1Ag57nQv8hOCI6shKyfa8qq53AsU9HmCoRg1E32I2Nucm5mWAQ43hz0XsxHng9ADiqi
    eD1CosG9PwAAA9BPvCZ6T7wmegAAAAdzc2gtcnNhAAABAQC5BLDU+4T0x9zn1zL2q2UTDt
    /mhO0uJMzHB+fihkYCsdd3zX+lTncLvbvu6wi2u9u15X+soxuTB4o39wG1JBeWzS2qm3nf
    qoDSS1rEVlV8y7GZs4c+fYj5DXfL2C9Acq0t8cHLnLw98BcOlHQg7vfdqHxAUG+R40TdQ+
    lUaUoQMRAQb3pEvh6rzU9mXifsy2w8+W58QFmOOacdsbWYYJrQhJWfGpSO/FXxy+D1qWcT
    TktluVWsYPC+Pjt4S0OqWgT87eoPga1fUCDnudC/yE4IjqyErJ9ryqrncCxT0eYKhGDUTf
    YjY25ybmZYBDjeHPRezEeeD0AOKqJ4PUKiwb0/AAAAAwEAAQAAAQBtUQoyLRIXluc8zHe+
    KvKjWgyMpUmGFBQyHMezneZLvUwz6uVahIvuEgKyXYhef4yHYrwXAqBONQxDmNwXbOXLIh
    uzS/2sW4+VsRRGIUSNYcTjraFhGMcPcBeyB1+T0q3kEY2Rgl/usKbO5IPg2ZD2FJClZ2Ek
    b4XGvlNknnk2KuTtbk9TnfN6QKz1d05a92DwItwlLeIPSloPfrKv81mb7x7AWvXkovuXpO
    IZgIKCrmx/LOhPrG6qUtK6GXPePk+6nS3nLz1gwdYE/Z9TepZwl2M+SnKpbUJXhGfAM3yG
    7/6ryj8KgTf8jirzdCVd006VIDrjz61OCJkl00SN/GwxAAAAgC0nCJrWkcupPNAyLol8Fc
    Rf3Etm861BsyZJ0ddmTscm1LGPIxjcggDxul8yKGVUUDLMBEGTAOjERXXpHtJ9o8YhNrNX
    3KFr/FYzxbwc9c2lh63iPtjYB9yBFpq3fDZiCV1AGdnVSQdMLFUyoD7RP1x0eP78E86C7a
    Ud2rTI7P2VAAAAgQDsEYNtkyRvigPJKY9ZPm1Kd9RQJicB7esw12mg3+IWkhkLfpbGozGn
    yoIHDXC3c8r3uClGlkT3mzeZtV2jOf0EqtwkFgxOOpaSart51hN8LGExPphBqeifHzMh7j
    kT9a2wNVkxpO3ykFewclrsN9GDTmgd8aJMtX/Ma3lRG/jdHQAAAIEAyKPCHbzsbEqGSxsT
    Wo9IkRR3xS1SHIA2fnXTEv9aZU7ZzA7CTie1yYvXlZxOqWMvm5I1m4SrqM4uR3IqDbYY60
    OqBsndAWw17AFW5sQWyRX2AE6Yy8ukRbEAa6TfF9p/aTv63u8WCn0lv2t3IMOybb4JUwvc
    jdAiA/tcpak1oQsAAAAWYmVocmVuZHNATm9ldGhlci5sb2NhbAECAwQF
    -----END OPENSSH PRIVATE KEY-----
